[package]
name = "aurgh"
version = "0.1.0"
authors = ["Kevin Hill <gkh998@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
duct = "0.13.3"
iter = "0.0.0"
itertools = "0.9.0"
